### ISSUE TITLE
missing 2 first character when receive message

### ISSUE THREAD

**Issue by yuanrahman** [pjde/delphi-mqtt#2]
i tried to compile and use it with XE10, but everytime i subscribe.. all incoming message was truncated first 2 char. Can you help me please?

thank you

**Comment by pjde** [comment]
The demo encodes / decodes the messages as UTF8Strings which prefix the 
strings with a 2 byte length.

Simply use normal strings or add a two byte length when sending.


Regards


Paul

------ Original Message ------

**Comment by yuanrahman** [comment]
Thank you for your fast response .. 
and yes the most easily is add 2 byte length when sending the message :)

yoe

**Comment by pjde** [comment]
You can use what every format you what. It is only the demo that uses 
UTF8String format

------ Original Message ------

**Comment by pjde** [comment]
Hi Yoe

Found that the component was using the ID field in all QOS states. It 
should not be preset when QOS = 0.


New version on the repository should fix issue.


Regards


Paul

------ Original Message ------
