### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by HStirler** [pjde/delphi-mqtt#3]
Hi!
Are there any plans to support SSL?

As far as I see (correctly, but this solution worked for me so far) public object "Link" in uMQTTComponents has to be "TSSLWSocket" and the constructor has to be modified to create an SSLContext object.

(of cource, this solution has to be a little bit prettier to match the bpl idea)

greetings,
hauke

**Comment by pjde** [comment]
Short answer is no.

You are right about changing the link component to the SSL version. Be 
careful with the certificates included in the ICS demos as most are out 
of date.


Also be sure you are using the latest version of the component (of 
around a month ago).


Regards


Paul 

------ Original Message ------
