### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by smarcuss** [pjde/delphi-mqtt#4]
Hello, is there a way to run this component on android? Thanks.

**Comment by pjde** [comment]
The only way I can think off is to use laztoapk and swap out the ICS 
components for the Android TCP versions.

Don't know if it would work.

------ Original Message ------

**Comment by pjde** [comment]
I should add that I have not upgraded my Delphi since XE so don't know 
if the latest Delphi has ICS components for Android.

------ Original Message ------

**Comment by smarcuss** [comment]
ICS is not yet compatible with Android. I read the next version will be. Thanks for the answers.
